version: "3"

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: app_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volumes:/data/db

  app:
    build: .
    container_name: app_secrets
    depends_on:
      - mongodb
    environment:
      - CLIENT_ADDRESS_AND_PORT=mongodb://mongodb:27017/
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/code/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_volumes: